CREATE TABLE ENTRY
(
	ENTR_ID NUMBER NOT NULL,
	ENTR_CALC_TYPE VARCHAR2(20 BYTE) NOT NULL,
	ENTR_VALUE NUMBER NOT NULL,
	ENTR_ITER NUMBER NOT NULL,
	CONSTRAINT ENTRY_PK PRIMARY KEY (ENTR_ID) USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
)
TABLESPACE KVWS_PROFIL;

CREATE TABLE RESULT
(
	RES_ID NUMBER NOT NULL,
	ENTR_ID NUMBER NOT NULL,
	RES_CALC_TYPE VARCHAR2(20 BYTE) NOT NULL,
	RES_VALUE NUMBER NOT NULL,
	RES_TIME NUMBER NOT NULL,
	RES_DATE DATE NOT NULL,
	CONSTRAINT RESULT_PK PRIMARY KEY (RES_ID) USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
)
TABLESPACE KVWS_PROFIL;

COMMENT ON COLUMN ENTRY.ENTR_ID IS 'The entry ID.';
COMMENT ON COLUMN ENTRY.ENTR_CALC_TYPE IS 'The calculation type for the entry.';
COMMENT ON COLUMN ENTRY.ENTR_VALUE IS 'The entry value.';
COMMENT ON COLUMN ENTRY.ENTR_ITER IS 'The number of iterations for the entry';

COMMENT ON COLUMN RESULT.RES_ID IS 'The result id.';
COMMENT ON COLUMN RESULT.ENTR_ID IS 'The entry id.';
COMMENT ON COLUMN RESULT.RES_CALC_TYPE IS 'The calculation type of the result.';
COMMENT ON COLUMN RESULT.RES_VALUE IS 'The result value.';
COMMENT ON COLUMN RESULT.RES_TIME IS 'The spent time of calculation in milliseconds.';
COMMENT ON COLUMN RESULT.RES_DATE IS 'The date of calculation.';

ALTER TABLE RESULT
ADD CONSTRAINT RESULT_FK_ENTRY
FOREIGN KEY (ENTR_ID) REFERENCES ENTRY (ENTR_ID) ON DELETE Cascade;