CREATE SEQUENCE entry_entr_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE SEQUENCE result_res_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE ENTRY (
  ENTR_ID INTEGER PRIMARY KEY NOT NULL DEFAULT nextval('entry_entr_id_seq'::regclass),
  ENTR_CALC_TYPE CHARACTER VARYING(20) NOT NULL,
  ENTR_VALUE INTEGER NOT NULL,
  ENTR_ITER INTEGER NOT NULL
);
CREATE UNIQUE INDEX unique_entr_id ON entry USING BTREE (entr_id);

CREATE TABLE RESULT (
  RES_ID INTEGER PRIMARY KEY NOT NULL DEFAULT nextval('result_res_id_seq'::regclass),
  ENTR_ID INTEGER NOT NULL,
  RES_CALC_TYPE CHARACTER VARYING(20) NOT NULL,
  RES_VALUE INTEGER NOT NULL,
  RES_TIME INTEGER NOT NULL,
  RES_DATE DATE NOT NULL
);
CREATE UNIQUE INDEX unique_res_id ON result USING BTREE (res_id);

COMMENT ON COLUMN ENTRY.entr_id IS 'The entry ID.';
COMMENT ON COLUMN ENTRY.entr_calc_type IS 'The calculation type for the entry.';
COMMENT ON COLUMN ENTRY.entr_value IS 'The entry value.';
COMMENT ON COLUMN ENTRY.entr_iter IS 'The number of iterations for the entry';

COMMENT ON COLUMN RESULT.res_id IS 'The result id.';
COMMENT ON COLUMN RESULT.entr_id IS 'The entry id.';
COMMENT ON COLUMN RESULT.res_calc_type IS 'The calculation type of the result.';
COMMENT ON COLUMN RESULT.res_value IS 'The result value.';
COMMENT ON COLUMN RESULT.res_time IS 'The spent time of calculation in milliseconds.';
COMMENT ON COLUMN RESULT.res_date IS 'The date of calculation.';

ALTER TABLE RESULT
ADD CONSTRAINT RESULT_FK_ENTRY
FOREIGN KEY (ENTR_ID) REFERENCES ENTRY (ENTR_ID) ON DELETE Cascade;